// import "./index.css";
// import Header from "@/components/header";
// import Footer from "@/components/footer";
// import { CartProvider } from "@/context/CartContext";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* CartProvider SAB se upar hona chahiye */}
//         <CartProvider>
//           <Header />
//           {children}
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// }


"use client";

import "./index.css";
import { CartProvider } from "@/context/CartContext";
import Header from "@/components/header";
import Footer from "@/components/footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
